# -*- coding: utf-8 -*-
"""Dane treści dla generatora podstron usług: python3 scripts/build_service_pages.py"""

SERVICE_PAGES: list[dict] = []

def _svc(**kw: object) -> None:
    SERVICE_PAGES.append(kw)


_svc(
    file="usluga-koordynacja-budowy.html",
    title="Koordynacja budowy — KBN Signature Homes",
    meta_desc="Kierownik budowy KBN — harmonogram, ekipy, odbiory i komunikacja z branżami na Podkarpaciu.",
    hero_img_w2000="https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=2000&q=80",
    breadcrumb="Koordynacja budowy",
    h1_inner="""Koordynacja budowy <span>od pierwszej łopaty</span> do ostatniego protokołu""",
    lead="Harmonogram, logistyka placu, komunikacja z instalatorami i wykonawcami oraz jasny raport co tydzień — Ty decydujesz, "
    "my pilnujemy, żeby każdy etap domknął się na czas i w ramach kosztów.",
    metrics=(
        ("1 kierownik", "Jedna osoba kontaktu z pełnym mandatem"),
        ("48 h", "Odpowiedź na blokady formalne i dostawy krytyczne"),
        ("Pełny PM", "Od spotkania projektowego po odbiór komisji"),
    ),
    intro_tag="Dlaczego KBN",
    intro_h2="""Chaos nie buduje się w weekend — <span>my też nie pozwalamy</span> mu wejść na plac""",
    intro_p1="Łączymy znajomość polskiego rynku materiałów i podwykonawców z amerykańską kulturą statusów i RACI — "
    "każdy zna swoją kartę odwiedzin i kolejki branż. Dokumentację i zdjęcia z budowy dostajesz na wzór raportu inwestora.",
    intro_p2="Przy nowych domach lub dużych modernizacjach zaczynamy od mapy krytycznej ścieżki (critical path) — "
    "to tam zwykle giną tygodnie, jeżeli nie ma kogoś pilnującego.",
    bullets=[
        "Cotygodniowy mail + krótki call z budowy lub biura pola",
        "Protokół odbiorów elektrycznych, hydraulicznych i budowlanych w jednym miejscu",
        "Walidacja materiałów przed kolejnym przysiomem ekip — mniej dublowania transportów",
        "Asystujemy przy przeglądzie gwarancji i przeglądach rocznych po przekazaniu",
    ],
    aside_h3="Harmonogram to umowa między nami",
    aside_p="Rezerwujemy slot dla kierownika minimum 90 dni przed ruszeniem koparki na typowym projekcie. "
    "W sezonie wiosenno-letnim grafik bywa pełniejszy — warto odezwać się z wyprzedzeniem.",
    pkg_subtitle="Przykład przy domu jednorodzinnym ~180&nbsp;m² i realizacji ok. 11–13 miesięcy (Podkarpacie). "
    "Dokładną prognozę i widełki liczymy po audycie projektu oraz działki.",
    pkg_note="Ceny netto ± VAT. Pakiety zakładają współpracę z nami jako wykonawcą lub koordynatorem na placu u Twojego generalnego. "
    "Nie obejmują opłat administracyjnych ZUD — przekażemy listę w pierwszym tygodniu.",
    p1_tier="Pakiet 01",
    p1_name="Brief + plan startu",
    p1_price="od 17 900 zł",
    p1_price_small="&nbsp;<small>jednorazowo netto za harmonogram krytyczny</small>",
    p1_desc="Do startu koparki: przegląd dokumentacji BOQ-lite, kalendarz przyjazdów ekip oraz pierwszy miesiąc raportowy z dostępem do kierownika.",
    p1_features=[
        "Mapa zależności branż + agenda spotkań z podwykonawcami",
        "Rejestr zatwierdzonych materiałów krytycznych (okna / prąd)",
        "2 wizyty na placu lub wideokontrola etapów",
    ],
    p1_btn="Wybieram Brief",
    p2_tier="Pakiet 02",
    p2_name="Signature PM",
    p2_price="od 11 900 zł",
    p2_price_small="&nbsp;<small>miesięcznie netto przy umowie 8+ miesięcy</small>",
    p2_desc="Pełna opieka placu jak w inwestycji deweloperskiej: briefingi dla ekip, koordynacja dostaw, raport foto i zarządzanie zmianami w zakresie.",
    p2_features=[
        "Arkusz postępu + dokumentacja foto w chmurze",
        "Obecność lub reprezentacja na odbiorach z nadzorem / bankiem",
        "Zsynchronizowana koordynacja z instalacjami KBN przy wspólnej umowie",
    ],
    p2_btn="Rezerwuję Signature PM",
    p3_tier="Pakiet 03",
    p3_name="Inwest Premium",
    p3_price="od 279 900 zł",
    p3_price_small="&nbsp;<small>cena całkowita netto — pełne PM pod klucz</small>",
    p3_desc="Zdejmujemy zarządzanie budową z barków przy domu premium lub nietypowych technologiach (BIM, rekuperacja, automatyka wielostrefowa).",
    p3_features=[
        "Dedykowany kierownik + back-office dokumentacji dla banku",
        "Audyt każdego aneksu cenowego przed akceptacją",
        "Przygotowanie pod przekazanie do inteligentnego domu lub facility",
    ],
    p3_btn="Zaplanuj Inwest Premium",
    gallery_h2="""Harmonogram <span>w obiektywie</span>""",
    gallery_sub="Chwile odbiorów i etapów, które trudno ogarnąć zdalnie — dokumentujemy je tak, jak dla zarządu inwestora.",
    gallery_imgs=[
        ("https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1600&q=80", "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=900&q=80", "Inżynier na budowie z dokumentacją"),
        ("https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&q=80", "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&q=75", "Konstrukcja i etap robót dachowych"),
        ("https://images.unsplash.com/photo-1770625467638-964f594712e3?w=1200&q=80", "https://images.unsplash.com/photo-1770625467638-964f594712e3?w=600&q=75", "Planowanie harmonogramu prac"),
        ("https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&q=80", "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&q=75", "Spotkanie robocze przy projekcie"),
        ("https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=1200&q=80", "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&q=75", "Roboty fundamentowe na placu"),
        ("https://images.unsplash.com/photo-1565008576549-57569a49371d?w=1200&q=80", "https://images.unsplash.com/photo-1565008576549-57569a49371d?w=600&q=75", "Porządek i oznakowanie BHP na budowie"),
    ],
    cta_h2="""Potrzebujesz <span>kapitana placu</span> z referencjami, nie przypadkowego nadzoru?""",
    cta_p="Napisz, na jakim etapie jesteś — przygotujemy mikro-harmonogram na 21 dni i widełki kosztów opieki PM.",
)

_svc(
    file="usluga-instalacje-elektryczne-hydrauliczne.html",
    title="Instalacje elektryczne i hydrauliczne — KBN Signature Homes",
    meta_desc="Projekt i wykonanie instalacji elektrycznych, wod-kan i C.O. z rozdzielnicami, pomiarami i protokołami — Podkarpacie.",
    hero_img_w2000="https://images.unsplash.com/photo-1741177364447-f79669c51f12?w=2000&q=80",
    breadcrumb="Instalacje elektryczne & hydrauliczne",
    h1_inner="""Instalacje <span>elektryczne i hydrauliczne</span> — projekt, wykonanie, pomiary""",
    lead="Nowoczesne okablowanie, rozdzielnice z opisanymi obwodami, instalacje wod-kan i C.O. pod Twoją armaturową — zgodnie z normami, "
    "bez improwizacji w ścianach zamkniętych na lata.",
    metrics=(
        ("PEF / WT", "Przewidujemy obciążenia pod rekuperację, pompę i EV"),
        ("Protokoły", "Pomiary izolacji i szczelności przed odbiorem"),
        ("1 zespół", "Elektryka i hydraulika zsynchronizowane z budową KBN"),
    ),
    intro_tag="Dlaczego KBN",
    intro_h2="""Instalacje to <span>niewidzialna jakość</span> domu — robimy je widzialne w dokumentacji""",
    intro_p1="Wykonujemy komplet podtynkowy z opisanymi punktami, zdjęciami tras przed zasypaniem i listą obwodów zgodną z rozdzielnicą. "
    "Nie zostawiamy „drutów na później”.",
    intro_p2="Przy współpracy z budową KBN wiemy dokładnie, kiedy wpada strop, kiedy zawieszamy GK i kiedy krzyżują się instalacje — unikamy kolizji i dodatkowych bruzd.",
    bullets=[
        "Rozdzielnica z opisem RCD / MCB i rezerwą na Smart Home",
        "Trasy kablowe i rury z zachowaniem promieni i odstępów termicznych",
        "Przyłącza pod pompę ciepła, rekuperację i ładowarkę EV — na etapie projektu",
        "Odbiory z protokołami — gotowe pod inspekcję i uruchomienie urządzeń",
    ],
    aside_h3="Dobry moment na uzgodnienia",
    aside_p="Najwcześniej po zamknięciu projektu architektonicznego — wtedy optymalizujemy trasy i skrzytki. "
    "Przy przebudowach liczymy też obciążenie istniejącej rozdzielnicy.",
    pkg_subtitle="Orientacja przy domu ~180&nbsp;m², standard KBN, Podkarpacie — dokładna wycena po projekcie instalacyjnym lub inwentaryzacji.",
    pkg_note="Ceny netto ± VAT. Nie obejmują kosztów projektu branżowego od zewnętrznej pracowni, chyba że umówimy go w pakiecie. "
    "Dopłaty za nietypowe materiały (szyny, złącza premium) w osobnym koszyku.",
    p1_tier="Pakiet 01",
    p1_name="Core",
    p1_price="od 198 zł",
    p1_price_small="&nbsp;<small>za m² pow. użytkową — instalacja elektryczna podstawowa</small>",
    p1_desc="Komplet podtynkowy: obwody oświetleniowe i gniazda wg uzgodnionej listy, rozdzielnica, uziemienie, opis obwodów.",
    p1_features=[
        "Do 45 punktów elektrycznych w standardzie (powyżej wg koszyka)",
        "Pomiarówka i protokół odbioru przed tynkami",
        "Koordynacja z ekipą budowlaną KBN",
    ],
    p1_btn="Wybieram Core",
    p2_tier="Pakiet 02",
    p2_name="Signature MEP",
    p2_price="od 312 zł",
    p2_price_small="&nbsp;<small>za m² PU — elektryka + wod-kan + C.O. rozprowadzone</small>",
    p2_desc="Wszystko z Core plus komplet hydrauliki i ogrzewania podłogowego w strefie dzienniej, zasilanie pod rekuperację i klimę.",
    p2_features=[
        "Rury w piance, zawory odcinające opisane na szafce",
        "Przygotowanie pod zmiękczacz / stację filtrów",
        "Wspólna dokumentacja foto tras przed zasypaniem",
    ],
    p2_btn="Rezerwuję Signature MEP",
    p3_tier="Pakiet 03",
    p3_name="Smart-ready",
    p3_price="od 428 zł",
    p3_price_small="&nbsp;<small>za m² PU — szyny, DALI, BUS, EV, osprzęt premium</small>",
    p3_desc="Instalacja pod inteligentny dom: więcej obwodów LED, szyny, okablowanie sterujące, gniazda sieciowe i zasilanie ładowarki.",
    p3_features=[
        "Listy punktów zgodnych z wybranym systemem sterowania",
        "Dodatkowe obwody i zasilanie dla gastronomii lub spa",
        "Szafka RACK / centrala niskiego napięcia wg projektu",
    ],
    p3_btn="Zaplanuj Smart-ready",
    gallery_h2="""Instalacje <span>przed zamknięciem ścian</span>""",
    gallery_sub="Moment, którego nie widać po wykończeniu — dokumentujemy trasy dokładnie, żeby późniejszy montaż nie był loterią.",
    gallery_imgs=[
        ("https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=1600&q=80", "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=900&q=80", "Montaż tablicy rozdzielczej elektrycznej"),
        ("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=1200&q=80", "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=75", "Rury instalacji wodnej w ścianie"),
        ("https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80", "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=75", "Hydraulika i zawory na stelażach"),
        ("https://images.unsplash.com/photo-1542361345-89e58247f2d5?w=1200&q=80", "https://images.unsplash.com/photo-1542361345-89e58247f2d5?w=600&q=75", "Przewody elektryczne w nowym domu"),
        ("https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80", "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=75", "Węzły sanitarnące i kolektory"),
        ("https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=1200&q=80", "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&q=75", "Izolacja termiczna rur C.O."),
    ],
    cta_h2="""Masz projekt elektryczny <span>od architekta</span> czy dopiero powstaje?""",
    cta_p="Przyślij PDF lub wizytę na placu — w 48 godzin wrócimy z listą uwag oraz widełkami dla trzech zakresów.",
)

_svc(
    file="usluga-pompa-fotowoltaika.html",
    title="Pompa ciepła i fotowoltaika — KBN Signature Homes",
    meta_desc="Pompa ciepła, instalacja fotowoltaiczna i magazyn energii — dobór urządzeń, przyłącza i dokumentacja powykonawcza.",
    hero_img_w2000="https://images.unsplash.com/photo-1509391366360-2e959784a276?w=2000&q=80",
    breadcrumb="Pompa ciepła & fotowoltaika",
    h1_inner="""Pompa ciepła <span>+ fotowoltaika</span> — niższe rachunki, mniejsza emisja""",
    lead="Profil obciążenia, moce modułów i magazynu dopasujemy do Twojego zużycia i budynku WT 2021 — od pierwszego konsultingu po uruchomienie z dokumentacją do ZE.",
    metrics=(
        ("SCOP-ready", "Dobór jednostki przy typowych stratach TWOJEJ izolacji"),
        ("EPC", "Komplet protokołów po stronie przyłącza i falownika"),
        ("Gwarancje", "Rejestracje urządzeń i przegląd po sezonie grzewczym"),
    ),
    intro_tag="Dlaczego KBN",
    intro_h2="""Nie montujemy <span>tabel z internetu</span> — liczymy na Twoich danych""",
    intro_p1="Łączymy dobór gruntowej / powietrznej pompy z instalacją wykonaną przez naszą ekipę MEP oraz z przyszłością rozbudowy o PV i magazyn.",
    intro_p2="Dbamy o poprawny tor od skrzynki AC po miejsca postojowe pod wallbox — inwestycja ma się kleić przy całej elektryce domu.",
    bullets=[
        "Symulacja rocznego COP i pokrycia PV na podstawie orientacji dachu",
        "Hydranty / odprowadzenia skraplania zgodnie z kartą jednostki",
        "Komunikacja z ZE i przygotowanie pod Dwukierunkowy licznik (gdy dostępne)",
        "Szkolenie z obsługi sterownika po uruchomieniu",
    ],
    aside_h3="Ulgi i dokumenty",
    aside_p="Pomożemy uporządkować zestaw dokumentów do ulg i certyfikatów — lista zależy od miesiąca i programu.",
    pkg_subtitle="Przykład dla domu ~180&nbsp;m², powietrzna pompa ok. 8–12 kW i instalacja elektryczna przygotowana przez nas lub audytowana.",
    pkg_note="Ceny netto ± VAT. Nie zawierają opłat przyłączeniowych zakładu energetycznego ani geologii przy pompie gruntowej.",
    p1_tier="Pakiet 01",
    p1_name="Heat Solo",
    p1_price="od 54 900 zł",
    p1_price_small="&nbsp;<small>netto — pompa powietrzna, montaż, pierwszy rozruch</small>",
    p1_desc="Jednostka split lub monoblok wg doboru, montaż media, podstawowy sterownik, protokół szczelności i uruchomienie.",
    p1_features=[
        "Dobór mocy na podstawie audytu izolacji",
        "Instalacja hydrantów i zabezpieczeń zgodnie z protokołem producenta",
        "Dokumentacja powykonawcza do odbioru",
    ],
    p1_btn="Wybieram Heat Solo",
    p2_tier="Pakiet 02",
    p2_name="Solar Synergy",
    p2_price="od 96 500 zł",
    p2_price_small="&nbsp;<small>netto — pompa + PV ok. 6–8 kWp + monitoring produkcji</small>",
    p2_desc="Łączymy źródło ciepła z fotowoltaiką i optymalizujemy parametry pracy falownika pod domowe zużycie.",
    p2_features=[
        "Konstrukcja dachowa lub gruntowa modułów — po analizie nośności",
        "Integracja z istniejącą rozdzielnicą lub rozbudowa obwodów",
        "Konsultacja magazynu jako opcji rozbudowy",
    ],
    p2_btn="Rezerwuję Solar Synergy",
    p3_tier="Pakiet 03",
    p3_name="Full Grid+",
    p3_price="od 149 900 zł",
    p3_price_small="&nbsp;<small>netto — PV 10 kWp klasa, magazyn 10 kWh, EMS</small>",
    p3_desc="Pakiet dla domów wysokoenergetycznych z AC, basenem lub ładowarkami — priorytetyzacja obciążeń i monitoring w aplikacji.",
    p3_features=[
        "Sterowanie kierowaniem energii (self-consumption)",
        "Przygotowanie pod V2H / wallboxy (obwody zabezpieczeniowe)",
        "Roczny przegląd instalacji w ramach pierwszego sezonu",
    ],
    p3_btn="Zaplanuj Full Grid+",
    gallery_h2="""Energia <span>na dachu i w szafce</span>""",
    gallery_sub="Realizacje łączące moduły, jednostki zewnętrzne i estetyczne ukrycie okablowania.",
    gallery_imgs=[
        ("https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=1600&q=80", "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=900&q=80", "Panele fotowoltaiczne na dachu domu"),
        ("https://images.unsplash.com/photo-1617103996702-96ff29b1c467?w=1200&q=80", "https://images.unsplash.com/photo-1617103996702-96ff29b1c467?w=600&q=75", "Jednostka zewnętrzna pompy ciepła"),
        ("https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=1200&q=80", "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=600&q=75", "Ładowarka EV przy garażu"),
        ("https://images.unsplash.com/photo-1510511459019-5dda7724fd87?w=1200&q=80", "https://images.unsplash.com/photo-1510511459019-5dda7724fd87?w=600&q=75", "Inwerter i okablowanie AC"),
        ("https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=1200&q=80", "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&q=75", "Magazyn energii w garażu"),
        ("https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=1200&q=80", "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=600&q=75", "Wiatraki i energia odnawialna — inspiracja"),
    ],
    cta_h2="""Chcesz wiedzieć, <span>co realnie zwróci się</span> w 10 lat?""",
    cta_p="Wyślij roczne zużycie lub projekt CO — przygotujemy scenariusze „tylko pompa” vs „pompa + PV + magazyn”.",
)

_svc(
    file="usluga-rekuperacja-klimatyzacja.html",
    title="Rekuperacja i klimatyzacja — KBN Signature Homes",
    meta_desc="Rekuperacja z odzyskiem ciepła i klimatyzacja precyzyjna — projekt przebiegu kanałów, montaż i balans powietrza.",
    hero_img_w2000="https://images.unsplash.com/photo-1765850262030-1ae93e474473?w=2000&q=80",
    breadcrumb="Rekuperacja & klimatyzacja",
    h1_inner="""Rekuperacja <span>i klimatyzacja</span> — świeże powietrze bez utraty energii""",
    lead="Wybieramy centrale i jednostki wewnętrzne pod Twój obieg powietrza i poziom hałasu. Montaż kanałów planujemy jeszcze przed sufitem, "
    "żeby mieć zapas wysokości i czysty balans.",
    metrics=(
        ("ACH", "Tłumienie przecieków przy oknach KBN lub audycie"),
        ("ΔT", "Nawiewy i wywiewy ustawiane na obiegu docelowym"),
        ("Quiet", "Kalkulacja dB przy sypialni i salonie"),
    ),
    intro_tag="Dlaczego KBN",
    intro_h2="""Wtłaczamy <span>higienę klimatu</span> tak samo jak ciepło rozdzielnicy""",
    intro_p1="Łączymy rekuperację z instalacją MEP oraz z przyszłą automatyką — przewidujemy sloty czujników CO₂ i jakości powietrza.",
    intro_p2="Przy jednostkach multisplit lub klimie kanałowej zsynchronizujemy przepływy z rekuperatorami, żeby nie walczyły o ciśnienie.",
    bullets=[
        "Model 3D kanałów lub szczegół na podstawie rzutów BIM",
        "Filtry dostępne bez wchodzenia na stryp — projektowany serwis",
        "Bypass letni i ochrona przed przegrzewaniem w szachtach",
        "Protokół balansowania po uruchomieniu",
    ],
    aside_h3="Moment na decyzje",
    aside_p="Najlepiej przed zawieszeniem sufitów podwieszanych — wtedy kanały idą prosto i cicho. Przy stropach monolitycznych liczymy na wcześniejsze frezowanie tras.",
    pkg_subtitle="Orientacja dla domu ~180&nbsp;m², centrala ok. 250–350 m³/h i klimatyzacja 3–4 stref (Split lub kanałowa).",
    pkg_note="Ceny netto ± VAT. Nie obejmują kominków z otwartą komorą spalania wymagających dodatkowych wyrównań ciśnień projektowych.",
    p1_tier="Pakiet 01",
    p1_name="Vent Core",
    p1_price="od 42 900 zł",
    p1_price_small="&nbsp;<small>netto — rekuperacja, kanały, nawiewy PODSTAWOWE</small>",
    p1_desc="Komplet przygotowania pod rekuperator, kanały PCV/flex wg projektu, nawiewniki ścienne, podłączenie elektryczne i rozruch.",
    p1_features=[
        "Dobór centrale + filtry",
        "Koordynacja z izolacyjnością budynku przy testach prostych",
        "Instrukcja serwisu filtrów",
    ],
    p1_btn="Wybieram Vent Core",
    p2_tier="Pakiet 02",
    p2_name="Climate Signature",
    p2_price="od 71 900 zł",
    p2_price_small="&nbsp;<small>netto — rekuperacja + klima 3 wewnętrznych</small>",
    p2_desc="Łączenie z odprowadzeniem skroplin, obejścia kondensatu do kanalizacji i obwody zasilające pod naszą elektrykę.",
    p2_features=[
        "Rozdział stref dziennych i nocnych",
        "Reduktory hałasu w kluczowych odcinkach",
        "Integracja z magistralą Smart Home (opcja)",
    ],
    p2_btn="Rezerwuję Climate Signature",
    p3_tier="Pakiet 03",
    p3_name="Silent Duct",
    p3_price="od 118 000 zł",
    p3_price_small="&nbsp;<small>netto — kanałowa pełna + rekuperacja premium</small>",
    p3_desc="Dla domów z wysokimi wnętrzami i wymaganiami akustycznymi — kanały izolowane, strefy z precyzyjnymi przepływami.",
    p3_features=[
        "Modele obciążenia cieplnego latem / zimą",
        "Projekt serwisowy krat i klap",
        "Rezerwa na oczyszczacz / nawilżacz adiabatyczny",
    ],
    p3_btn="Zaplanuj Silent Duct",
    gallery_h2="""Kanały, <span>których nie widać</span>""",
    gallery_sub="Detale montażu rekuperacji i jednostek wewnętrznych w nowych domach KBN.",
    gallery_imgs=[
        ("https://images.unsplash.com/photo-1617103996702-96ff29b1c467?w=1600&q=80", "https://images.unsplash.com/photo-1617103996702-96ff29b1c467?w=900&q=80", "Kanały wentylacyjne w suficie"),
        ("https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=1200&q=80", "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&q=75", "Montaż instalacji i izolacji"),
        ("https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1200&q=80", "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&q=75", "Jednostka klimatyzacji na elewacji"),
        ("https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200&q=80", "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=600&q=75", "Sterownik klimatyzacji na ścianie"),
        ("https://images.unsplash.com/photo-1617103996702-96ff29b1c467?w=1200&q=80", "https://images.unsplash.com/photo-1617103996702-96ff29b1c467?w=600&q=75", "Nawiewnik w ścianie lub oknie"),
        ("https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1200&q=80", "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&q=75", "Prace instalacyjne w nowym domu"),
    ],
    cta_h2="""Nie wiesz, <span>czy rekuperacja</span> zmieści się pod sufitem napinanym?""",
    cta_p="Przyślij przekrój wiązara lub profil sufitu — dostaniesz zestaw ostrzeżeń i rekomendacji zanim zamówisz sufity.",
)

_svc(
    file="usluga-automatyka-domowa.html",
    title="Automatyka domowa — KBN Signature Homes",
    meta_desc="Smart Home od KBN — oświetlenie rolety, HVAC, sterowanie scenami i integracja z alarmem — Podkarpacie.",
    hero_img_w2000="https://images.unsplash.com/photo-1770625467638-964f594712e3?w=2000&q=80",
    breadcrumb="Automatyka domowa",
    h1_inner="""Automatyka domowa <span>pod Twoje sceny</span> — jeden ekran, zero chaosu""",
    lead="Projektujemy magistrale, bramki i strefy sterowania tak, aby można było rozbudować dom o kolejne czujniki bez przerabiania całej instalacji.",
    metrics=(
        ("BUS / IP", "Topologie z rezerwą na przyszłe moduły"),
        ("Bezpieczeństwo", "Segmentacja sieci gości / automatyka"),
        ("Wsparcie", "30 dni tuningu scen po przekazaniu"),
    ),
    intro_tag="Dlaczego KBN",
    intro_h2="""Smart Home <span>to nie apk</span> — to poprawnie poprowadzona infrastruktura""",
    intro_p1="Łączymy przewody sterujące, zasilanie urządzeń brzegowych i konfigurację z realnym użytkowaniem — światło, rolety, temperatura, powiadomienia.",
    intro_p2="Przy integracji z rekuperacją, pompą i PV synchronizujemy scenariusze oszczędzania z komfortem — bez konfliktu sterowników.",
    bullets=[
        "Dokumentacja adresów i scen z wersją PDF + backup",
        "Testy fail-safe (awaria internetu / reset zasilania)",
        "Szkolenie mieszkańców + krótki film instruktażowy",
        "Rezerwa portów na przyszłe systemy audio lub monitoring",
    ],
    aside_h3="Kiedy zamawiać",
    aside_p="Najpóźniej na etapie instalacji elektrycznej — wcześniej ustalamy skrzynki i zasilanie dla bramki i serwera L2.",
    pkg_subtitle="Dom ~180&nbsp;m², 3 strefy dzienne + sypialnie — skalowalne pakiety pod KNX, Z-Wave lub hybrydę producenta po uzgodnieniu.",
    pkg_note="Ceny netto ± VAT. Licencje chmurowe producentów i subskrypcje monitoringu po stronie dostawcy — poza pakietem, chyba że umówione inaczej.",
    p1_tier="Pakiet 01",
    p1_name="Essential UI",
    p1_price="od 24 900 zł",
    p1_price_small="&nbsp;<small>netto — oświetlenie, rolety, 1 bramka</small>",
    p1_desc="Sterowanie podstawowymi obwodami LED, roletami zewnętrznymi i jednym panelem dotykowym w strefie wejścia.",
    p1_features=[
        "Mapa obwodów zgodna z rozdzielnicą",
        "Sceny „Wyjście” i „Noc”",
        "Integracja z pilotami producenta",
    ],
    p1_btn="Wybieram Essential UI",
    p2_tier="Pakiet 02",
    p2_name="Signature Living",
    p2_price="od 58 900 zł",
    p2_price_small="&nbsp;<small>netto — HVAC, bojler, czujniki, app</small>",
    p2_desc="Rozszerzenie o strefy temperatury, sterowanie zaworami, czujniki temperatury i wilgotności, powiadomienia push.",
    p2_features=[
        "Integracja z rekuperacją / pompą jeśli wykonane przez KBN",
        "Panel ścienny w salonie + dostęp mobilny",
        "Backup konfiguracji na nośniku Klienta",
    ],
    p2_btn="Rezerwuję Signature Living",
    p3_tier="Pakiet 03",
    p3_name="Pro Resilience",
    p3_price="od 129 900 zł",
    p3_price_small="&nbsp;<small>netto — KNX + redundancja + AV-ready</small>",
    p3_desc="Dla domów flagship: magistrale KNX / IP, redundancyjne zasilanie logiki i przygotowanie pod multiroom oraz monitoring ONVIF.",
    p3_features=[
        "VLAN dla automatyki i gości sieciowych",
        "Integracja alarmu i kamer przy współpracy z działem security",
        "12 miesięcy pierwszeństwa SLA konfiguracyjnego",
    ],
    p3_btn="Zaplanuj Pro Resilience",
    gallery_h2="""Sterowanie, <span>które widać tylko gdy chcesz</span>""",
    gallery_sub="Panele ścienne, zabudowy techniczne i testy pierwszych scen po wykończeniu.",
    gallery_imgs=[
        ("https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=1600&q=80", "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=900&q=80", "Nowoczesny panel sterowania światłem"),
        ("https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=1200&q=80", "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=600&q=75", "Interior z inteligentnym oświetleniem LED"),
        ("https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=75", "Kuchnia premium z automatyką"),
        ("https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=1200&q=80", "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=600&q=75", "Salon inteligentnego domu"),
        ("https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=75", "Detale oświetlenia rezydencjalnego"),
        ("https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&q=80", "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=75", "Wyświetlacz i przyciski przy wejściu"),
    ],
    cta_h2="""Masz ulubiony ekosystem <span>sprzętowy</span> czy chcesz neutralnie?""",
    cta_p="Opisz urządzenia, których nie chcesz wymieniać — dobierzemy mostki i zamówienia instalacyjne pod nie.",
)

_svc(
    file="usluga-monitoring-alarm.html",
    title="Monitoring i alarm — KBN Signature Homes",
    meta_desc="Monitoring CCTV, alarm antywłamaniowy i domofonia IP — dobór pozycji kamer, okablowanie PoE i integracja aplikacji.",
    hero_img_w2000="https://images.unsplash.com/photo-1723187024776-e3d4f6627e22?w=2000&q=80",
    breadcrumb="Monitoring & alarm",
    h1_inner="""Monitoring CCTV <span>+ alarm</span> — wizualna i elektroniczna warstwa bezpieczeństwa""",
    lead="Planujemy widoczność przy wejściu, podjeździe i ogrodzeniu bez martwych pól — z doborem rozdzielczości dziennej i nocnej oraz retencją nagrań pod Twoją politykę archiwum.",
    metrics=(
        ("POE+", "Liczenie budgetu zasilania i switchy zarządzalnych"),
        ("ONVIF", "Otwarta integracja dla przyszłej rozbudowy"),
        ("RLS-ready", "Przygotowanie pod czujki zewnętrzne Dual"),
    ),
    intro_tag="Dlaczego KBN",
    intro_h2="""„Później dokładamy kamerę” <span>to najdroższa opcja</span> po tynku""",
    intro_p1="Wyznaczamy trasę ethernetu i zasilania jeszcze przy instalacji elektrycznej — rejestrator w technicznej, dyski z RAID lub cold backup.",
    intro_p2="Integrujemy wideodomofon z automatyką (otwarcie furtki, sceny powitalne) jeśli oba systemy realizujemy w KBN.",
    bullets=[
        "Modele ognisk i wysokości montażu z symulacją FOV",
        "Strefy detekcji — ograniczenie fałszywych alarmów",
        "Polityka haseł i kont użytkowników zgodna z RODO technicznym",
        "Szkolenie z eksportu nagrań dla insurance",
    ],
    aside_h3="Prawo i sąsiedzi",
    aside_p="Pomagamy ustalić orientacyjnie zasięg widoczności względem granic — ostateczna odpowiedzialność formalna po stronie inwestora i prawnika.",
    pkg_subtitle="Dom jednorodzinny ~180&nbsp;m², podjazd, ogród, wejście główne — przykładowe pakiety kamer 4 / 8 / 12 MP.",
    pkg_note="Ceny netto ± VAT. Abonamenty chmury producenta i monitoringu GSM — opcjonalnie, poza kwotą pakietu.",
    p1_tier="Pakiet 01",
    p1_name="Watch 4",
    p1_price="od 9 800 zł",
    p1_price_small="&nbsp;<small>netto — 4 kamery POE + rejestrator 4K</small>",
    p1_desc="Kamery tubowe lub kopułkowe z IR, rejestrator z dyskiem 4 TB, podstawowa aplikacja mobilna.",
    p1_features=[
        "Trasy kablowe i patchpanel w szafce RACK / technicznej",
        "Podstawowa konfiguracja detekcji ruchu",
        "Instrukcja eksportu nagrań",
    ],
    p1_btn="Wybieram Watch 4",
    p2_tier="Pakiet 02",
    p2_name="Secure 8",
    p2_price="od 19 400 zł",
    p2_price_small="&nbsp;<small>netto — 8 kamer + alarm 16 stref</small>",
    p2_desc="Rozszerzenie o czujki magnetyczne, PIR wewnętrzne, sygnalizator zewnętrzny i powiadomienia GSM.",
    p2_features=[
        "Integracja z kontaktronami bram",
        "Rezerwa obwodów na czujki dymu (jeśli system adresowy)",
        "Testy sabotażu przed odbiorem",
    ],
    p2_btn="Rezerwuję Secure 8",
    p3_tier="Pakiet 03",
    p3_name="Estate Shield",
    p3_price="od 36 900 zł",
    p3_price_small="&nbsp;<small>netto — analityka, LPR-ready, redundancja</small>",
    p3_desc="Dla większych posesji: liczenie linii, detekcja wtargnięcia w strefy ogrodu, kamera LPR na podjeździe, dyski mirroring.",
    p3_features=[
        "Zarządzalny switch i segmentacja VLAN",
        "Integracja z automatyką KBN (sceny alarmowe)",
        "Doradztwo ubezpieczeniowe techniczne (listy kontrolne)",
    ],
    p3_btn="Zaplanuj Estate Shield",
    gallery_h2="""Pola widzenia <span>i detale montażu</span>""",
    gallery_sub="Realizacje kamer zewnętrznych, szaf rack oraz integracja z domofonem.",
    gallery_imgs=[
        ("https://images.unsplash.com/photo-1723187024776-e3d4f6627e22?w=1600&q=80", "https://images.unsplash.com/photo-1723187024776-e3d4f6627e22?w=900&q=80", "Kamera monitoringu na elewacji"),
        ("https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200&q=80", "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=600&q=75", "Wideodomofon przy wejściu"),
        ("https://images.unsplash.com/photo-1551808525-51a94da548ce?w=1200&q=80", "https://images.unsplash.com/photo-1551808525-51a94da548ce?w=600&q=75", "Pokój kontroli z ekranami"),
        ("https://images.unsplash.com/photo-1510511459019-5dda7724fd87?w=1200&q=80", "https://images.unsplash.com/photo-1510511459019-5dda7724fd87?w=600&q=75", "Switch sieciowy i okablowanie"),
        ("https://images.unsplash.com/photo-1765850262030-1ae93e474473?w=1200&q=80", "https://images.unsplash.com/photo-1765850262030-1ae93e474473?w=600&q=75", "Kamera PTZ na maszcie"),
        ("https://images.unsplash.com/photo-1617103996702-96ff29b1c467?w=1200&q=80", "https://images.unsplash.com/photo-1617103996702-96ff29b1c467?w=600&q=75", "Monitoring posesji domowej"),
    ],
    cta_h2="""Ile <span>metrów kabla</span> realnie potrzebujesz do archiwum 30 dni?""",
    cta_p="Podaj liczbę kamer i rozdzielczość — policzymy dyski i przepustowość switcha, zanim kupisz sprzęt „w promocji”.",
)

_svc(
    file="usluga-wykonczenia-pod-klucz.html",
    title="Wykończenia pod klucz — KBN Signature Homes",
    meta_desc="Wykończenie wnętrz pod klucz — tynki, podłogi, stolarka, łazienki i odbiory — z harmonogramem KBN na Podkarpaciu.",
    hero_img_w2000="https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=2000&q=80",
    breadcrumb="Wykończenia pod klucz",
    h1_inner="""Wykończenia <span>pod klucz</span> — od gładzi po ostatnią listwę""",
    lead="Łączymy prace budowlane z wykończeniami w jednym harmonogramie — nie tracisz tygodni na „przestój po otynkowaniu”. Jakość materiałów i kolejność ekip pilnuje opiekun KBN.",
    metrics=(
        ("Zero-lag", "Zakotwiczenie prac wykończeniowych w budowie"),
        ("Checklisty", "Odbiory pomieszczeń etapami"),
        ("Gwarancje", "Protokoły producentów okien, podłóg i farb"),
    ),
    intro_tag="Dlaczego KBN",
    intro_h2="""Ten sam zespół, który <span>zna ściany</span> — nie zgadujemy co jest pod tynkiem""",
    intro_p1="Znamy każdą ścianę, bo często ją sami zbudowaliśmy — nie ma niespodzianek z kołkami chemicznymi ani wilgocią po paroizolacji.",
    intro_p2="Listy materiałów synchronizujemy z projektem wnętrz lub z Tobą na moodboardach — kontrolujemy kompatybilność klejów, mas i posadzek.",
    bullets=[
        "Harmonogram z szynami sufitowymi i oświetleniem punktowym",
        "Łazienki w standardzie spójnym z armaturą z naszego katalogu partnerskiego",
        "Odbiór wilgotności podłóg przed montaem paneli",
        "Porządne zabezpieczenie stolarki przed innymi ekipami",
    ],
    aside_h3="Start po surowcu",
    aside_p="Najlepiej 2–3 tygodnie przed planowanym końcem tynków — wtedy rezerwujemy ekipy szpachlarskie i montażowe bez luki kalendarzowej.",
    pkg_subtitle="Dom ~180&nbsp;m² PU, jedna kondygnacja mieszkalna + antresola — orientacyjne widełki za m² po audycie materiałowym.",
    pkg_note="Ceny netto ± VAT. Meble kuchenne na wymiar i sprzęt AGD — w koszyku dodatkowym lub z Twojego dostawcy z naszym montażem.",
    p1_tier="Pakiet 01",
    p1_name="Move-in Base",
    p1_price="od 2 580 zł",
    p1_price_small="&nbsp;<small>za m² PU — gładzie, farby, panele, listwy</small>",
    p1_desc="Wykończenie techniczne gotowe do wprowadzenia mebli z IKEA / sklepu — bez zabudów na wymiar.",
    p1_features=[
        "Tynki gipsowe + gładzie premium",
        "Podłogi laminat / winyl LVT wg koszyka",
        "Pierwsze sprzątanie builderskie",
    ],
    p1_btn="Wybieram Move-in Base",
    p2_tier="Pakiet 02",
    p2_name="Signature Finish",
    p2_price="od 3 420 zł",
    p2_price_small="&nbsp;<small>za m² PU — łazienki premium, drzwi, led</small>",
    p2_desc="Komplet łazienek w gresie 60×120, armatura stal nierdzewna, drzwi wewnętrzne, szyny sufitowe z LED.",
    p2_features=[
        "Nadzór koordynatora wnętrz KBN",
        "Pomiary wilgotności i odbiory pokojowe",
        "Rezerwa budżetowa na podłogi hybrydowe premium",
    ],
    p2_btn="Rezerwuję Signature Finish",
    p3_tier="Pakiet 03",
    p3_name="Bespoke Living",
    p3_price="od 4 890 zł",
    p3_price_small="&nbsp;<small>za m² PU — zabudowy, fornir, kamień</small>",
    p3_desc="Indywidualne zabudowy meblowe, okładziny ścienne, detale stolarskie i akustyka pod soft furnishing.",
    p3_features=[
        "Warsztat stolarski partnerski na wymiar",
        "Bookmatch kamienia i detale narożników",
        "Aranżacja finałowa przed sesją foto",
    ],
    p3_btn="Zaplanuj Bespoke Living",
    gallery_h2="""Detale, <span>które domykają</span> wrażenie""",
    gallery_sub="Łazienki, podłogi i zabudowy z realizacji KBN — spójne z budową i instalacjami.",
    gallery_imgs=[
        ("https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1600&q=80", "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=900&q=80", "Jasny salon z dużym przeszkleniem"),
        ("https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1200&q=80", "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=600&q=75", "Łazienka z prysznicem walk-in"),
        ("https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=75", "Kuchnia z wyspą w nowym domu"),
        ("https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&q=80", "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&q=75", "Wnętrze z naturalnym światłem"),
        ("https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&q=80", "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=600&q=75", "Schody i balustrada w domu"),
        ("https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1200&q=80", "https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=600&q=75", "Minimalistyczna sypialnia"),
    ],
    cta_h2="""Masz już <span>wizualizacje</span> czy dopiero inspiracje z Pinterest?""",
    cta_p="Przy wyborze pakietu Signature/Bespoke przygotujemy koszyk próbek materiałów w ciągu 7 dni po spotkaniu.",
)

_svc(
    file="usluga-projektowanie-wnetrz.html",
    title="Projektowanie wnętrz — KBN Signature Homes",
    meta_desc="Projekt wnętrz 3D, dobór materiałów i realizacja koordynowana — KBN Signature Homes, Podkarpacie.",
    hero_img_w2000="https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=2000&q=80",
    breadcrumb="Projektowanie wnętrz",
    h1_inner="""Projektowanie wnętrz <span>pod Twój rytm dnia</span> — wizualizacja + lista zakupów""",
    lead="Tworzymy koncepty, które da się policzyć i zbudować — bez mebli „z kosmosu” i bez konfliktu z instalacjami, które już prowadzimy na budowie.",
    metrics=(
        ("3D", "Wizualizacje z natężeniem światła realnego"),
        ("FF&E", "Lista przedmiotów z linkami i symbolami"),
        ("Build", "Koordynacja z naszymi ekipami wykończeniowymi"),
    ),
    intro_tag="Dlaczego KBN",
    intro_h2="""Projekt to nie render — <span>to harmonogram</span> dostaw szczegółów""",
    intro_p1="Wiemy, jak długo czeka się na laminaty XL i na zamówienia blatów — zakładamy bufory materiałowe w dokumentacji dla Ciebie i budowy.",
    intro_p2="Jeśli KBN realizuje instalacje i wykończenia, projektanci siedzą z kierownikami przy jednym stole — zmianę obwodu Ledy widzisz w tej samej wersji rysunku.",
    bullets=[
        "Inwentaryza laserowa jeśli pracujemy na istniejącej bryle",
        "Opisy wykończeń dla przetargów i porównania",
        "Konsultacja akustyczna uproszczona dla mieszkań dzieci",
        "Współpraca z dostawcami mebli kuchennych na wymiar",
    ],
    aside_h3="Kiedy start",
    aside_p="Najlepiej miesiąc przed wiechą lub przed gruntownym wyburzeniem przegród — dostosujemy ściany i punty elektryczne do ustawienia mebli.",
    pkg_subtitle="Mieszkanie lub dom rzędu ~90–220&nbsp;m² — pakiety liczone za m² powierzchni projektowej (bez tarasów otwartych).",
    pkg_note="Ceny netto ± VAT. Wyjazdy poza Podkarpacie i nadgodziny na budowie w godzinach 22–6 — wg stawki kilometrowej lub umowy.",
    p1_tier="Pakiet 01",
    p1_name="Concept",
    p1_price="od 95 zł",
    p1_price_small="&nbsp;<small>za m² PU — moodboard + układ funkcjonalny 2 iteracje</small>",
    p1_desc="Dwa warianty rozmieszczenia mebla kluczowego oraz tablica materiałów z kartami cenowymi orientacyjnymi.",
    p1_features=[
        "Rzuty czarno-białe CAD",
        "Moodboardy online",
        "Wideokonsultacje lub 2 spotkania stacjonarne",
    ],
    p1_btn="Wybieram Concept",
    p2_tier="Pakiet 02",
    p2_name="Interior Signature",
    p2_price="od 215 zł",
    p2_price_small="&nbsp;<small>za m² PU — wiz 3D, specyfikacja, lista zakupów</small>",
    p2_desc="Komplet foto-realistyczny salonu + kluczowych sypialni, specyfikacja podłóg, ścian, oświetlenia i okładzin.",
    p2_features=[
        "Biblioteka modeli zsynchronizowana z wykonaniami KBN",
        "Raport kolizji z rekuperacją / sufitem podsufitkowym",
        "Jedna tura poprawek w zakresie WIZ gratis",
    ],
    p2_btn="Rezerwuję Interior Signature",
    p3_tier="Pakiet 03",
    p3_name="Design + Site",
    p3_price="od 395 zł",
    p3_price_small="&nbsp;<small>za m² PU — jak Signature + wizyty i nadzór</small>",
    p3_desc="Projekt „pod budowę” z detalami zamówień dla stolarza, wizyty powykonawcze, assist przy odbiorach końcowych.",
    p3_features=[
        "Komunikacja z brukarzem ogrodu przy ciągu wejść",
        "Dobór textile i sztuki w końcowej fazie",
        "Pakiet dokumentacji foto do celów marketingowych inwestora prywatnego",
    ],
    p3_btn="Zaplanuj Design + Site",
    gallery_h2="""Od tablicy <span>do</span> ostatniej poduszki""",
    gallery_sub="Wnętrza o różnych skalach — minimalistyczna baza i detale materiałowe dla domów KBN.",
    gallery_imgs=[
        ("https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1600&q=80", "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&q=80", "Salon designerski z sofą i oknem"),
        ("https://images.unsplash.com/photo-1615873968403-89e068629265?w=1200&q=80", "https://images.unsplash.com/photo-1615873968403-89e068629265?w=600&q=75", "Minimalistyczna jadalnia przy kuchni"),
        ("https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&q=80", "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=600&q=75", "Apartament loftowy z mikrocementem"),
        ("https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80", "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=600&q=75", "Kominek elektryczny w nowoczesnym salonie"),
        ("https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&q=80", "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&q=75", "Sypialnia z tapicerowanym panelem ściennym"),
        ("https://images.unsplash.com/photo-1615873968403-89e068629265?w=1200&q=80", "https://images.unsplash.com/photo-1615873968403-89e068629265?w=600&q=75", "Łazienka z okrągłym lustrem i gres XL"),
    ],
    cta_h2="""Wolisz wyglądać <span>jak katalog premium</span> czy rustykalny slow-living?""",
    cta_p="Prześlij 5 referencji z Instagrama oraz budżet mebli — wrócimy z propozycją pakietu i timeline prac graficznych.",
)
