# -*- coding: utf-8 -*-
"""Dane treści dla generatora podstron usług: python3 scripts/build_service_pages.py"""

SERVICE_PAGES: list[dict] = []

def _svc(**kw: object) -> None:
    SERVICE_PAGES.append(kw)


_svc(
    file="usluga-koordynacja-budowy.html",
    title="Koordynacja budowy — KBN Signature Homes",
    meta_desc="Kierownik budowy KBN — harmonogram, ekipy, odbiory i komunikacja z branżami na Podkarpaciu.",
    hero_img_w2000="https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=2000&q=80",
    breadcrumb="Koordynacja budowy",
    h1_inner="""Koordynacja budowy <span>od pierwszej łopaty</span> do ostatniego protokołu""",
    lead="Harmonogram, logistyka placu, komunikacja z instalatorami i wykonawcami oraz jasny raport co tydzień — Ty decydujesz, "
    "my pilnujemy, żeby każdy etap domknął się na czas i w ramach kosztów.",
    intro_tag="Dlaczego KBN",
    intro_h2="""Chaos nie buduje się w weekend — <span>my też nie pozwalamy</span> mu wejść na plac""",
    intro_p1="Łączymy znajomość polskiego rynku materiałów i podwykonawców z amerykańską kulturą statusów i RACI — "
    "każdy zna swoją kartę odwiedzin i kolejki branż. Dokumentację i zdjęcia z budowy dostajesz na wzór raportu inwestora.",
    intro_p2="Przy nowych domach lub dużych modernizacjach zaczynamy od mapy krytycznej ścieżki (critical path) — "
    "to tam zwykle giną tygodnie, jeżeli nie ma kogoś pilnującego.",
    bullets=[
        "Cotygodniowy mail + krótki call z budowy lub biura pola",
        "Protokół odbiorów elektrycznych, hydraulicznych i budowlanych w jednym miejscu",
        "Walidacja materiałów przed kolejnym przysiomem ekip — mniej dublowania transportów",
        "Asystujemy przy przeglądzie gwarancji i przeglądach rocznych po przekazaniu",
    ],
    aside_h3="Harmonogram to umowa między nami",
    aside_p="Rezerwujemy slot dla kierownika minimum 90 dni przed ruszeniem koparki na typowym projekcie. "
    "W sezonie wiosenno-letnim grafik bywa pełniejszy — warto odezwać się z wyprzedzeniem.",
    pkg_subtitle="Przykład przy domu jednorodzinnym ~180&nbsp;m² i realizacji ok. 11–13 miesięcy (Podkarpacie). "
    "Dokładną prognozę i widełki liczymy po audycie projektu oraz działki.",
    pkg_note="Ceny netto ± VAT. Pakiety zakładają współpracę z nami jako wykonawcą lub koordynatorem na placu u Twojego generalnego. "
    "Nie obejmują opłat administracyjnych ZUD — przekażemy listę w pierwszym tygodniu.",
    p1_tier="Pakiet 01",
    p1_name="Brief + plan startu",
    p1_price="od 17 900 zł",
    p1_price_small="&nbsp;<small>jednorazowo netto za harmonogram krytyczny</small>",
    p1_desc="Do startu koparki: przegląd dokumentacji BOQ-lite, kalendarz przyjazdów ekip oraz pierwszy miesiąc raportowy z dostępem do kierownika.",
    p1_features=[
        "Mapa zależności branż + agenda spotkań z podwykonawcami",
        "Rejestr zatwierdzonych materiałów krytycznych (okna / prąd)",
        "2 wizyty na placu lub wideokontrola etapów",
    ],
    p1_btn="Wybieram Brief",
    p2_tier="Pakiet 02",
    p2_name="Signature PM",
    p2_price="od 11 900 zł",
    p2_price_small="&nbsp;<small>miesięcznie netto przy umowie 8+ miesięcy</small>",
    p2_desc="Pełna opieka placu jak w inwestycji deweloperskiej: briefingi dla ekip, koordynacja dostaw, raport foto i zarządzanie zmianami w zakresie.",
    p2_features=[
        "Arkusz postępu + dokumentacja foto w chmurze",
        "Obecność lub reprezentacja na odbiorach z nadzorem / bankiem",
        "Zsynchronizowana koordynacja z instalacjami KBN przy wspólnej umowie",
    ],
    p2_btn="Rezerwuję Signature PM",
    p3_tier="Pakiet 03",
    p3_name="Inwest Premium",
    p3_price="od 279 900 zł",
    p3_price_small="&nbsp;<small>cena całkowita netto — pełne PM pod klucz</small>",
    p3_desc="Zdejmujemy zarządzanie budową z barków przy domu premium lub nietypowych technologiach (BIM, rekuperacja, automatyka wielostrefowa).",
    p3_features=[
        "Dedykowany kierownik + back-office dokumentacji dla banku",
        "Audyt każdego aneksu cenowego przed akceptacją",
        "Przygotowanie pod przekazanie do inteligentnego domu lub facility",
    ],
    p3_btn="Zaplanuj Inwest Premium",
    gallery_h2="""Harmonogram <span>w obiektywie</span>""",
    gallery_sub="Chwile odbiorów i etapów, które trudno ogarnąć zdalnie — dokumentujemy je tak, jak dla zarządu inwestora.",
    gallery_imgs=[
        ("https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1600&q=80", "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=900&q=80", "Inżynier na budowie z dokumentacją"),
        ("https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&q=80", "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&q=75", "Konstrukcja i etap robót dachowych"),
        ("https://images.unsplash.com/photo-1770625467638-964f594712e3?w=1200&q=80", "https://images.unsplash.com/photo-1770625467638-964f594712e3?w=600&q=75", "Planowanie harmonogramu prac"),
        ("https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&q=80", "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&q=75", "Spotkanie robocze przy projekcie"),
        ("https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=1200&q=80", "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&q=75", "Roboty fundamentowe na placu"),
        ("https://images.unsplash.com/photo-1565008576549-57569a49371d?w=1200&q=80", "https://images.unsplash.com/photo-1565008576549-57569a49371d?w=600&q=75", "Porządek i oznakowanie BHP na budowie"),
    ],
    cta_h2="""Potrzebujesz <span>kapitana placu</span> z referencjami, nie przypadkowego nadzoru?""",
    cta_p="Napisz, na jakim etapie jesteś — przygotujemy mikro-harmonogram na 21 dni i widełki kosztów opieki PM.",
)

_svc(
    file="usluga-instalacje-elektryczne.html",
    title="Instalacje elektryczne — KBN Signature Homes",
    meta_desc="Projekt i wykonanie instalacji elektrycznych: rozdzielnice, obwody, okablowanie Smart-ready i pomiary — Podkarpacie.",
    hero_img_w2000="https://images.unsplash.com/photo-1741177364447-f79669c51f12?w=2000&q=80",
    breadcrumb="Instalacje elektryczne",
    h1_inner="""Instalacje <span>elektryczne</span> — rozdzielnica, obwody, dokumentacja""",
    lead="Projektujemy i wykonujemy instalację elektryczną pod aktualne normy oraz przyszłą automatykę — bez „kanibalizowania” obwodów "
    "przy pierwszej rozbudowie.",
    intro_tag="Dlaczego KBN",
    intro_h2="""Elektryka to <span>fundament</span> każdego komfortu w domu""",
    intro_p1="Opisujemy każdy obwód w dokumentacji zgodnej z tablicą — nie „kartka odłożona na później”. Przed GK masz zestaw zdjęć tras.",
    intro_p2="Koordynujemy punkty z rekuperacją, klimatyzacją i EV tak, żeby nie dublować rozdzielni ani przeciążać faz bez świadomej decyzji.",
    bullets=[
        "Listy punktów zsynchronizowane z lightingiem architektonicznym",
        "Ułożenie kabli z promieniami zgodnymi z normą i kartami producentów",
        "Przewidywanie obciążenia pod storage PV lub wallbox — bez rewolucji po roku",
        "Protokoły odbiorów przygotowane pod Twojego inspektora lub rzeczoznawcę",
    ],
    aside_h3="Kiedy zamówić pomiary",
    aside_p="Zanim zamówisz tynki — wracamy na plac po zamknięciu obwodów, zanim zniknie dostęp do szachtów.",
    pkg_subtitle="Orientacja przy domu ~180&nbsp;m², Podkarpacie — dokładna wycena po liście punktów lub projekcie elektrycznym.",
    pkg_note="Ceny netto ± VAT. Nie obejmują opraw oświetleniowych ani szyn wpuszczanych — jako koszyk materiałowy po wyborze.",
    p1_tier="Pakiet 01",
    p1_name="Core Power",
    p1_price="od 198 zł",
    p1_price_small="&nbsp;<small>za m² PU — instalacja elektryczna podstawowa</small>",
    p1_desc="Komplet podtynkowy: obwody oświetleniowe i gniazda wg uzgodnionej listy, rozdzielnica, uziemienie, opis obwodów.",
    p1_features=[
        "Do 45 punktów elektrycznych w standardzie (powyżej wg koszyka)",
        "Pomiarówka i protokół przed tynkami",
        "Koordynacja z budową KBN lub Twoim kierownikiem",
    ],
    p1_btn="Wybieram Core Power",
    p2_tier="Pakiet 02",
    p2_name="LED Pro",
    p2_price="od 286 zł",
    p2_price_small="&nbsp;<small>za m² PU — więcej obwodów LED, DALI-ready</small>",
    p2_desc="Rozszerzenie o dodatkowe obwody modułowe, przygotowanie pod sterowanie centralne i sceny światła.",
    p2_features=[
        "Szyny wpuszczane lub natynkowe wg rzutu — ilość mb w koszyku",
        "Oddzielne obwody dla driverów i taśm premium",
        "Wsparcie przy wyborze temperatur barwowych i indeksów RA",
    ],
    p2_btn="Rezerwuję LED Pro",
    p3_tier="Pakiet 03",
    p3_name="Smart-ready",
    p3_price="od 428 zł",
    p3_price_small="&nbsp;<small>za m² PU — BUS, Ethernet, EV, RACK</small>",
    p3_desc="Instalacja pod inteligentny dom: więcej obwodów LED, szyny, okablowanie sterujące, sieć i zasilanie ładowarki.",
    p3_features=[
        "Adresacja punktów pod wybrany ekosystem sterowania",
        "Obwody pomocnicze dla gastronomii, SPA lub pokoju rack",
        "Szafka RACK lub miejsce na centralę LV wg uzgodnienia",
    ],
    p3_btn="Zaplanuj Smart-ready",
    gallery_h2="""Elektryka <span>przed zamknięciem ścian</span>""",
    gallery_sub="Tablice, koryta i opis obwodów — dokumentacja, która ratuje przy kolejnym remoncie.",
    gallery_imgs=[
        ("https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=1600&q=80", "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=900&q=80", "Montaż tablicy rozdzielczej elektrycznej"),
        ("https://images.unsplash.com/photo-1542361345-89e58247f2d5?w=1200&q=80", "https://images.unsplash.com/photo-1542361345-89e58247f2d5?w=600&q=75", "Przewody elektryczne w nowym domu"),
        ("https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=1200&q=80", "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&q=75", "Okablowanie i zabezpieczenia w rozdzielnicy"),
        ("https://images.unsplash.com/photo-1542361345-89e58247f2d5?w=1200&q=80", "https://images.unsplash.com/photo-1542361345-89e58247f2d5?w=600&q=75", "Trasy kablowe przed zasypaniem"),
        ("https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=1200&q=80", "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&q=75", "Detale montażu elektrycznego"),
        ("https://images.unsplash.com/photo-1542361345-89e58247f2d5?w=1200&q=80", "https://images.unsplash.com/photo-1542361345-89e58247f2d5?w=600&q=75", "Przygotowanie pod osprzęt"),
    ],
    cta_h2="""Masz już <span>projekt elektryczny</span> od pracowni?""",
    cta_p="Przyślij PDF — wrócimy z uwagami konstrukcyjnymi i trzema poziomami kosztu w 48 godzin.",
)

_svc(
    file="usluga-instalacje-hydrauliczne.html",
    title="Instalacje hydrauliczne — KBN Signature Homes",
    meta_desc="Wod-kan, C.O., instalacje sanitarne — projekt tras, materiały, izolacja akustyczna i dokumentacja foto — Podkarpacie.",
    hero_img_w2000="https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=2000&q=80",
    breadcrumb="Instalacje hydrauliczne",
    h1_inner="""Instalacje <span>hydrauliczne</span> — woda, kanalizacja, C.O.""",
    lead="Wykonujemy komplet instalacji wodnych i grzewczych z opisanymi zaworami, presją próbną i dokumentacją tras przed zabetonowaniem.",
    intro_tag="Dlaczego KBN",
    intro_h2="""Hydraulika ma być <span>cicha i serwisowalna</span>""",
    intro_p1="Projektujemy dostęp do kluczowych zaworów bez rozcinania mebli na stałe — szczególnie przy kolektorach i stacji uzdatniania.",
    intro_p2="Współpracujemy z rekuperacją i klimatyzacją przy odprowadzeniu skroplin oraz przy przygotowaniu pod źródła ciepła realizowane przez partnerów.",
    bullets=[
        "Opisy kolektorów i obiegów zgodne z rzutem łazienek",
        "Koordynacja poduszki pod stelaże WC i armaturę ścienną",
        "Rezerwy ciśnienia i przepływu pod przyszłe kurtyny deszczowe lub wanna-spa",
        "Zdjęcia tras archiwizowane w segregatorze powykonawczym",
    ],
    aside_h3="Najlepszy moment audytu",
    aside_p="Tuż po rozłożeniu tras i przed styropianem na podłodze — wtedy jeszcze bez kosztu demontu.",
    pkg_subtitle="Orientacja przy domu ~180&nbsp;m² z dwiema łazienkami — po rzucie sanitarnym lub wizji lokalnej.",
    pkg_note="Ceny netto ± VAT. Nie obejmują armatur poza podstawową listą ani kotłów uruchamianych przez SERWIS producenta poza KBN.",
    p1_tier="Pakiet 01",
    p1_name="Aqua Core",
    p1_price="od 92 zł",
    p1_price_small="&nbsp;<small>za m² PU — rozprowadzenie wod-kan podstawowe</small>",
    p1_desc="Komplet rur zimna/ciepła/kanalizacja w standardzie PP lub PEX wg projektu, bez przyłączy sprzętowych poza uzgodnioną listą.",
    p1_features=[
        "Izolacja akustyczna przewodów spływowych wg KBN",
        "Zawory odcinające opisane na szkicu",
        "Koordynacja z ekipą budowlaną lub Twoim nadzorem",
    ],
    p1_btn="Wybieram Aqua Core",
    p2_tier="Pakiet 02",
    p2_name="Thermo Floor",
    p2_price="od 154 zł",
    p2_price_small="&nbsp;<small>za m² PU — rozdzielacze + ogrzewanie podłogowe</small>",
    p2_desc="Obieg podłogowy z dociepleniem brzegów, pompowanie wirnikowe wg obliczeń i instrukcja rozruchu dla instalatora kotła.",
    p2_features=[
        "Regulacja długości pętli pod równomierny przepływ",
        "Przygotowanie pod zawory RTL w strefach dziennych",
        "Schemat kolektorowy z opisem dla serwisu",
    ],
    p2_btn="Rezerwuję Thermo Floor",
    p3_tier="Pakiet 03",
    p3_name="Sanitaire Plus",
    p3_price="od 218 zł",
    p3_price_small="&nbsp;<small>za m² PU — stelaże, przyłącza premium, filtracja</small>",
    p3_desc="Rozbudowa o przygotowanie pod stelaże Geberit-style, zestaw filtrów pod zlew i dodatkowe punkty czystej wody.",
    p3_features=[
        "Koordynacja poziomów z projektantem łazienki",
        "Większe średnice odpływu tam, gdzie projekt sanitarny na to pozwala",
        "Instalacja zestawów odpływowych pod brodziki typu walk-in",
    ],
    p3_btn="Zaplanuj Sanitaire Plus",
    gallery_h2="""Hydraulika <span>pod kontrolą ciszy</span>""",
    gallery_sub="Rury w pianie, kolektory opisane i dostęp serwisowy bez demolki.",
    gallery_imgs=[
        ("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=1600&q=80", "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=900&q=80", "Rury instalacji wodnej w ścianie"),
        ("https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80", "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=75", "Hydraulika i zawory na stelażach"),
        ("https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80", "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=75", "Węzły sanitarnące"),
        ("https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=1200&q=80", "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&q=75", "Izolacja termiczna rur C.O."),
        ("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=1200&q=80", "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=75", "Montaż instalacji w nowym domu"),
        ("https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80", "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=75", "Szczegół instalacji sanitarnej"),
    ],
    cta_h2="""Potrzebujesz <span>porównania materiałów</span> rur i izolacji?""",
    cta_p="Wyślij rzuty sanitarnych — zaproponujemy dwa warianty kosztowe z uzasadnieniem akustycznym.",
)

_svc(
    file="usluga-rekuperacja.html",
    title="Rekuperacja — KBN Signature Homes",
    meta_desc="Rekuperacja z odzyskiem ciepła — dobór centrale, montaż kanałów, balans powietrza i protokoły na Podkarpaciu.",
    hero_img_w2000="https://images.unsplash.com/photo-1765850262030-1ae93e474473?w=2000&q=80",
    breadcrumb="Rekuperacja",
    h1_inner="""Rekuperacja <span>z odzyskiem ciepła</span> — projekt, montaż, balans""",
    lead="Planujemy centralę, przebieg kanałów i nawiewników pod Twój ACH oraz oczekiwania akustyczne — zanim zamówisz sufity.",
    intro_tag="Dlaczego KBN",
    intro_h2="""Świeże powietrze <span>bez lottery</span> szachtów""",
    intro_p1="Łączymy projekt wentylacji z instalacją elektryczną i przygotowaniem pod automatykę czujników CO₂.",
    intro_p2="Jeżeli docelowo montujesz klimatyzację — synchronizujemy ciśnienia i obejścia, żeby instalacje nie „walczyły”.",
    bullets=[
        "Model przebiegu kanałów lub konsultacja BIM z Twoją pracownią",
        "Bypass letni i ochrona przed przegrzewaniem szachtów",
        "Instrukcje serwisu filtrów dla mieszkańców",
        "Protokół balansowania po uruchomieniu",
    ],
    aside_h3="Deadline pod sufity",
    aside_p="Minimum 10 dni roboczych przed montażem sufitów podwieszanych — inaczej kosztuje nas korekta tras.",
    pkg_subtitle="Dom ~180&nbsp;m², centrala 250–350 m³/h — orientacja przed zamówieniem sufitek.",
    pkg_note="Ceny netto ± VAT. Nie obejmują kominków z otwartą komorą ani dodatkowych kompensacji ciśnień projektowanych przez HVAC.",
    p1_tier="Pakiet 01",
    p1_name="Vent Core",
    p1_price="od 42 900 zł",
    p1_price_small="&nbsp;<small>netto — rekuperacja, kanały, nawiewy podstawowe</small>",
    p1_desc="Komplet przygotowania pod rekuperator, kanały wg projektu, nawiewniki ścienne, zasilanie i rozruch.",
    p1_features=[
        "Dobór centrale + zestaw filtrów startowych",
        "Podłączenie elektryczne zgodnie z kartą jednostki",
        "Instrukcja pierwszego przeglądu",
    ],
    p1_btn="Wybieram Vent Core",
    p2_tier="Pakiet 02",
    p2_name="Vent Acoustic",
    p2_price="od 58 400 zł",
    p2_price_small="&nbsp;<small>netto — redukcja hałasu przy sypialniach</small>",
    p2_desc="Rozszerzenie o tłumiki szczególne przy ścianach działowych oraz obejścia akustyczne kratek.",
    p2_features=[
        "Analiza hałasu przy progach drzwiowych",
        "Materiały tłumiące na odcinkach krytycznych",
        "Balans zapisany jako wartości docelowe na sterowniku",
    ],
    p2_btn="Rezerwuję Vent Acoustic",
    p3_tier="Pakiet 03",
    p3_name="Passive Flow",
    p3_price="od 89 900 zł",
    p3_price_small="&nbsp;<small>netto — instalacja premium + nadzór szczelności</small>",
    p3_desc="Dla domów energooszczędnych — dodatkowe testy prostoliniowości i dokumentacja pod audyt energetyczny.",
    p3_features=[
        "Wsparcie przy blower door razem z oknami KBN",
        "Rezerwa na oczyszczacz lub centralę wilgotności",
        "Harmonogram serwisowy na 24 miesiące",
    ],
    p3_btn="Zaplanuj Passive Flow",
    gallery_h2="""Rekuperacja <span>w detalach</span>""",
    gallery_sub="Kanały, izolacje i miejsca na filtry — bez improwizacji pod końcówkę budowy.",
    gallery_imgs=[
        ("https://images.unsplash.com/photo-1617103996702-96ff29b1c467?w=1600&q=80", "https://images.unsplash.com/photo-1617103996702-96ff29b1c467?w=900&q=80", "Kanały wentylacyjne w suficie"),
        ("https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=1200&q=80", "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&q=75", "Montaż instalacji i izolacji"),
        ("https://images.unsplash.com/photo-1617103996702-96ff29b1c467?w=1200&q=80", "https://images.unsplash.com/photo-1617103996702-96ff29b1c467?w=600&q=75", "Nawiewnik w ścianie lub oknie"),
        ("https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=1200&q=80", "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&q=75", "Roboty instalacyjne w szachtach"),
        ("https://images.unsplash.com/photo-1617103996702-96ff29b1c467?w=1200&q=80", "https://images.unsplash.com/photo-1617103996702-96ff29b1c467?w=600&q=75", "Centrala wentylacyjna na etapie montażu"),
        ("https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=1200&q=80", "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=600&q=75", "Izolacja przewodów wentylacyjnych"),
    ],
    cta_h2="""Masz już <span>wybrane okna</span> i nie chcesz trace leaks?""",
    cta_p="Wyślij rzut parteru — sprawdzimy, czy wywiewy są możliwe tam, gdzie projekt je zakłada.",
)

_svc(
    file="usluga-klimatyzacja.html",
    title="Klimatyzacja — KBN Signature Homes",
    meta_desc="Klimatyzacja split i kanałowa — dobór jednostek, odprowadzenie skroplin, integracja z elektryką — Podkarpacie.",
    hero_img_w2000="https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=2000&q=80",
    breadcrumb="Klimatyzacja",
    h1_inner="""Klimatyzacja <span>precyzyjna</span> — split, multisplit, kanałowa""",
    lead="Dobieramy jednostki pod Twój hałas dopuszczalny, fazę elektryczną i miejsce na jednostki zewnętrzne — zanim zamówisz elewację.",
    intro_tag="Dlaczego KBN",
    intro_h2="""Chłód ma być <span>równy</span> — nie lodowy w jednym pokoju""",
    intro_p1="Liczenie obciążenia na podstawie okien KBN lub Twojej specyfikacji szyb.",
    intro_p2="Jeżeli masz rekuperację od nas lub od partnera — synchronizujemy przepływy, żeby uniknąć podciśnienia lub „zatykania” nawiewów.",
    bullets=[
        "Wybór jednostek ściennych lub kanałowych pod architekturę wnętrza",
        "Trasy rurowe osłonięte lub wpuszczane wg uzgodnień z GK",
        "Obwody zasilające z opisem na rozdzielni",
        "Instrukcja serwisu filtrów jednostek wewnętrznych",
    ],
    aside_h3="Kiedy zamówić jednostki",
    aside_p="Po zamknięciu przegród działowych — wtedy wiemy dokładnie kubaturę stref.",
    pkg_subtitle="Dom ~180&nbsp;m² — orientacja dla 2–4 stref komfortu.",
    pkg_note="Ceny netto ± VAT. Nie obejmują kosztów podnośnika ani rusztowania przy trudnych elewacjach.",
    p1_tier="Pakiet 01",
    p1_name="Split Duo",
    p1_price="od 18 900 zł",
    p1_price_small="&nbsp;<small>netto — dwie jednostki wewnętrze + jedna zewnętrzna</small>",
    p1_desc="Idealny start dla dziennego i nocnego pomieszczenia — montaż mediów i pierwszy rozruch.",
    p1_features=[
        "Dobór mocy na podstawie kubatury",
        "Odprowadzenie skroplin zgodnie z rzutem",
        "Szablon serwisu dla mieszkańców",
    ],
    p1_btn="Wybieram Split Duo",
    p2_tier="Pakiet 02",
    p2_name="Multi Zone",
    p2_price="od 34 500 zł",
    p2_price_small="&nbsp;<small>netto — do czterech jednostek wewnętrznych</small>",
    p2_desc="Rozprowadzenie na kilka pokoi z jednego zestawu sprężarkowego i harmonogramem rozruchów.",
    p2_features=[
        "Optymalizacja długości linii czynnika",
        "Koordynacja otworów w ścianie nośnej z budową",
        "Integracja z rozdzielnicą KBN lub audyt Twojej tablicy",
    ],
    p2_btn="Rezerwuję Multi Zone",
    p3_tier="Pakiet 03",
    p3_name="Ducted Silent",
    p3_price="od 62 000 zł",
    p3_price_small="&nbsp;<small>netto — klimatyzacja kanałowa premium</small>",
    p3_desc="Ukryte jednostki za sufitem GK — dla architektur z wysokimi przeszkleniami.",
    p3_features=[
        "Analiza strat ciśnienia na kolanach i reduktorach",
        "Reduktory hałasu przy sypialniach",
        "Koordynacja kratek z projektantem wnętrz",
    ],
    p3_btn="Zaplanuj Ducted Silent",
    gallery_h2="""Klimatyzacja <span>bez chaosu</span> na elewacji""",
    gallery_sub="Jednostki zewnętrzne, trasowanie oraz sterowniki — spójnie z elektryką KBN.",
    gallery_imgs=[
        ("https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1600&q=80", "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=900&q=80", "Jednostka klimatyzacji na elewacji"),
        ("https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200&q=80", "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=600&q=75", "Sterownik klimatyzacji na ścianie"),
        ("https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1200&q=80", "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&q=75", "Montaż jednostki zewnętrznej"),
        ("https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200&q=80", "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=600&q=75", "Panel sterujący"),
        ("https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1200&q=80", "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&q=75", "Instalacja klimatyzacji na budowie"),
        ("https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200&q=80", "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=600&q=75", "Konfiguracja systemu"),
    ],
    cta_h2="""Nie wiesz, <span>split czy kanał</span> pod sufitem GK?""",
    cta_p="Wyślij rzuty — dostaniesz rekomendację z uzasadnieniem kosztowym i akustycznym.",
)

_svc(
    file="usluga-automatyka-domowa.html",
    title="Automatyka domowa — KBN Signature Homes",
    meta_desc="Smart Home od KBN — oświetlenie rolety, HVAC, sterowanie scenami i integracja z alarmem — Podkarpacie.",
    hero_img_w2000="https://images.unsplash.com/photo-1770625467638-964f594712e3?w=2000&q=80",
    breadcrumb="Automatyka domowa",
    h1_inner="""Automatyka domowa <span>pod Twoje sceny</span> — jeden ekran, zero chaosu""",
    lead="Projektujemy magistrale, bramki i strefy sterowania tak, aby można było rozbudować dom o kolejne czujniki bez przerabiania całej instalacji.",
    intro_tag="Dlaczego KBN",
    intro_h2="""Smart Home <span>to nie apk</span> — to poprawnie poprowadzona infrastruktura""",
    intro_p1="Łączymy przewody sterujące, zasilanie urządzeń brzegowych i konfigurację z realnym użytkowaniem — światło, rolety, temperatura, powiadomienia.",
    intro_p2="Przy integracji z rekuperacją, klimatyzacją i PV synchronizujemy scenariusze oszczędzania z komfortem — bez konfliktu sterowników.",
    bullets=[
        "Dokumentacja adresów i scen z wersją PDF + backup",
        "Testy fail-safe (awaria internetu / reset zasilania)",
        "Szkolenie mieszkańców + krótki film instruktażowy",
        "Rezerwa portów na przyszłe systemy audio lub monitoring",
    ],
    aside_h3="Kiedy zamawiać",
    aside_p="Najpóźniej na etapie instalacji elektrycznej — wcześniej ustalamy skrzynki i zasilanie dla bramki i serwera L2.",
    pkg_subtitle="Dom ~180&nbsp;m², 3 strefy dzienne + sypialnie — skalowalne pakiety pod KNX, Z-Wave lub hybrydę producenta po uzgodnieniu.",
    pkg_note="Ceny netto ± VAT. Licencje chmurowe producentów i subskrypcje monitoringu po stronie dostawcy — poza pakietem, chyba że umówione inaczej.",
    p1_tier="Pakiet 01",
    p1_name="Essential UI",
    p1_price="od 24 900 zł",
    p1_price_small="&nbsp;<small>netto — oświetlenie, rolety, 1 bramka</small>",
    p1_desc="Sterowanie podstawowymi obwodami LED, roletami zewnętrznymi i jednym panelem dotykowym w strefie wejścia.",
    p1_features=[
        "Mapa obwodów zgodna z rozdzielnicą",
        "Sceny „Wyjście” i „Noc”",
        "Integracja z pilotami producenta",
    ],
    p1_btn="Wybieram Essential UI",
    p2_tier="Pakiet 02",
    p2_name="Signature Living",
    p2_price="od 58 900 zł",
    p2_price_small="&nbsp;<small>netto — HVAC, bojler, czujniki, app</small>",
    p2_desc="Rozszerzenie o strefy temperatury, sterowanie zaworami, czujniki temperatury i wilgotności, powiadomienia push.",
    p2_features=[
        "Integracja z rekuperacją / klimatyzacją jeśli wykonane przez KBN",
        "Panel ścienny w salonie + dostęp mobilny",
        "Backup konfiguracji na nośniku Klienta",
    ],
    p2_btn="Rezerwuję Signature Living",
    p3_tier="Pakiet 03",
    p3_name="Pro Resilience",
    p3_price="od 129 900 zł",
    p3_price_small="&nbsp;<small>netto — KNX + redundancja + AV-ready</small>",
    p3_desc="Dla domów flagship: magistrale KNX / IP, redundancyjne zasilanie logiki i przygotowanie pod multiroom oraz monitoring ONVIF.",
    p3_features=[
        "VLAN dla automatyki i gości sieciowych",
        "Integracja alarmu i kamer przy współpracy z działem security",
        "12 miesięcy pierwszeństwa SLA konfiguracyjnego",
    ],
    p3_btn="Zaplanuj Pro Resilience",
    gallery_h2="""Sterowanie, <span>które widać tylko gdy chcesz</span>""",
    gallery_sub="Panele ścienne, zabudowy techniczne i testy pierwszych scen po wykończeniu.",
    gallery_imgs=[
        ("https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=1600&q=80", "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=900&q=80", "Nowoczesny panel sterowania światłem"),
        ("https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=1200&q=80", "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=600&q=75", "Interior z inteligentnym oświetleniem LED"),
        ("https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=75", "Kuchnia premium z automatyką"),
        ("https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=1200&q=80", "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=600&q=75", "Salon inteligentnego domu"),
        ("https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=75", "Detale oświetlenia rezydencjalnego"),
        ("https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&q=80", "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=75", "Wyświetlacz i przyciski przy wejściu"),
    ],
    cta_h2="""Masz ulubiony ekosystem <span>sprzętowy</span> czy chcesz neutralnie?""",
    cta_p="Opisz urządzenia, których nie chcesz wymieniać — dobierzemy mostki i zamówienia instalacyjne pod nie.",
)

_svc(
    file="usluga-monitoring-alarm.html",
    title="Monitoring i alarm — KBN Signature Homes",
    meta_desc="Monitoring CCTV, alarm antywłamaniowy i domofonia IP — dobór pozycji kamer, okablowanie PoE i integracja aplikacji.",
    hero_img_w2000="https://images.unsplash.com/photo-1723187024776-e3d4f6627e22?w=2000&q=80",
    breadcrumb="Monitoring & alarm",
    h1_inner="""Monitoring CCTV <span>+ alarm</span> — wizualna i elektroniczna warstwa bezpieczeństwa""",
    lead="Planujemy widoczność przy wejściu, podjeździe i ogrodzeniu bez martwych pól — z doborem rozdzielczości dziennej i nocnej oraz retencją nagrań pod Twoją politykę archiwum.",
    intro_tag="Dlaczego KBN",
    intro_h2="""„Później dokładamy kamerę” <span>to najdroższa opcja</span> po tynku""",
    intro_p1="Wyznaczamy trasę ethernetu i zasilania jeszcze przy instalacji elektrycznej — rejestrator w technicznej, dyski z RAID lub cold backup.",
    intro_p2="Integrujemy wideodomofon z automatyką (otwarcie furtki, sceny powitalne) jeśli oba systemy realizujemy w KBN.",
    bullets=[
        "Modele ognisk i wysokości montażu z symulacją FOV",
        "Strefy detekcji — ograniczenie fałszywych alarmów",
        "Polityka haseł i kont użytkowników zgodna z RODO technicznym",
        "Szkolenie z eksportu nagrań dla insurance",
    ],
    aside_h3="Prawo i sąsiedzi",
    aside_p="Pomagamy ustalić orientacyjnie zasięg widoczności względem granic — ostateczna odpowiedzialność formalna po stronie inwestora i prawnika.",
    pkg_subtitle="Dom jednorodzinny ~180&nbsp;m², podjazd, ogród, wejście główne — przykładowe pakiety kamer 4 / 8 / 12 MP.",
    pkg_note="Ceny netto ± VAT. Abonamenty chmury producenta i monitoringu GSM — opcjonalnie, poza kwotą pakietu.",
    p1_tier="Pakiet 01",
    p1_name="Watch 4",
    p1_price="od 9 800 zł",
    p1_price_small="&nbsp;<small>netto — 4 kamery POE + rejestrator 4K</small>",
    p1_desc="Kamery tubowe lub kopułkowe z IR, rejestrator z dyskiem 4 TB, podstawowa aplikacja mobilna.",
    p1_features=[
        "Trasy kablowe i patchpanel w szafce RACK / technicznej",
        "Podstawowa konfiguracja detekcji ruchu",
        "Instrukcja eksportu nagrań",
    ],
    p1_btn="Wybieram Watch 4",
    p2_tier="Pakiet 02",
    p2_name="Secure 8",
    p2_price="od 19 400 zł",
    p2_price_small="&nbsp;<small>netto — 8 kamer + alarm 16 stref</small>",
    p2_desc="Rozszerzenie o czujki magnetyczne, PIR wewnętrzne, sygnalizator zewnętrzny i powiadomienia GSM.",
    p2_features=[
        "Integracja z kontaktronami bram",
        "Rezerwa obwodów na czujki dymu (jeśli system adresowy)",
        "Testy sabotażu przed odbiorem",
    ],
    p2_btn="Rezerwuję Secure 8",
    p3_tier="Pakiet 03",
    p3_name="Estate Shield",
    p3_price="od 36 900 zł",
    p3_price_small="&nbsp;<small>netto — analityka, LPR-ready, redundancja</small>",
    p3_desc="Dla większych posesji: liczenie linii, detekcja wtargnięcia w strefy ogrodu, kamera LPR na podjeździe, dyski mirroring.",
    p3_features=[
        "Zarządzalny switch i segmentacja VLAN",
        "Integracja z automatyką KBN (sceny alarmowe)",
        "Doradztwo ubezpieczeniowe techniczne (listy kontrolne)",
    ],
    p3_btn="Zaplanuj Estate Shield",
    gallery_h2="""Pola widzenia <span>i detale montażu</span>""",
    gallery_sub="Realizacje kamer zewnętrznych, szaf rack oraz integracja z domofonem.",
    gallery_imgs=[
        ("https://images.unsplash.com/photo-1723187024776-e3d4f6627e22?w=1600&q=80", "https://images.unsplash.com/photo-1723187024776-e3d4f6627e22?w=900&q=80", "Kamera monitoringu na elewacji"),
        ("https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200&q=80", "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=600&q=75", "Wideodomofon przy wejściu"),
        ("https://images.unsplash.com/photo-1551808525-51a94da548ce?w=1200&q=80", "https://images.unsplash.com/photo-1551808525-51a94da548ce?w=600&q=75", "Pokój kontroli z ekranami"),
        ("https://images.unsplash.com/photo-1510511459019-5dda7724fd87?w=1200&q=80", "https://images.unsplash.com/photo-1510511459019-5dda7724fd87?w=600&q=75", "Switch sieciowy i okablowanie"),
        ("https://images.unsplash.com/photo-1765850262030-1ae93e474473?w=1200&q=80", "https://images.unsplash.com/photo-1765850262030-1ae93e474473?w=600&q=75", "Kamera PTZ na maszcie"),
        ("https://images.unsplash.com/photo-1617103996702-96ff29b1c467?w=1200&q=80", "https://images.unsplash.com/photo-1617103996702-96ff29b1c467?w=600&q=75", "Monitoring posesji domowej"),
    ],
    cta_h2="""Ile <span>metrów kabla</span> realnie potrzebujesz do archiwum 30 dni?""",
    cta_p="Podaj liczbę kamer i rozdzielczość — policzymy dyski i przepustowość switcha, zanim kupisz sprzęt „w promocji”.",
)

_svc(
    file="usluga-wykonczenia-pod-klucz.html",
    title="Wykończenia pod klucz — KBN Signature Homes",
    meta_desc="Wykończenie wnętrz pod klucz — tynki, podłogi, stolarka, łazienki i odbiory — z harmonogramem KBN na Podkarpaciu.",
    hero_img_w2000="https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=2000&q=80",
    breadcrumb="Wykończenia pod klucz",
    h1_inner="""Wykończenia <span>pod klucz</span> — od gładzi po ostatnią listwę""",
    lead="Łączymy prace budowlane z wykończeniami w jednym harmonogramie — nie tracisz tygodni na „przestój po otynkowaniu”. Jakość materiałów i kolejność ekip pilnuje opiekun KBN.",
    intro_tag="Dlaczego KBN",
    intro_h2="""Ten sam zespół, który <span>zna ściany</span> — nie zgadujemy co jest pod tynkiem""",
    intro_p1="Znamy każdą ścianę, bo często ją sami zbudowaliśmy — nie ma niespodzianek z kołkami chemicznymi ani wilgocią po paroizolacji.",
    intro_p2="Listy materiałów synchronizujemy z projektem wnętrz lub z Tobą na moodboardach — kontrolujemy kompatybilność klejów, mas i posadzek.",
    bullets=[
        "Harmonogram z szynami sufitowymi i oświetleniem punktowym",
        "Łazienki w standardzie spójnym z armaturą z naszego katalogu partnerskiego",
        "Odbiór wilgotności podłóg przed montaem paneli",
        "Porządne zabezpieczenie stolarki przed innymi ekipami",
    ],
    aside_h3="Start po surowcu",
    aside_p="Najlepiej 2–3 tygodnie przed planowanym końcem tynków — wtedy rezerwujemy ekipy szpachlarskie i montażowe bez luki kalendarzowej.",
    pkg_subtitle="Dom ~180&nbsp;m² PU, jedna kondygnacja mieszkalna + antresola — orientacyjne widełki za m² po audycie materiałowym.",
    pkg_note="Ceny netto ± VAT. Meble kuchenne na wymiar i sprzęt AGD — w koszyku dodatkowym lub z Twojego dostawcy z naszym montażem.",
    p1_tier="Pakiet 01",
    p1_name="Move-in Base",
    p1_price="od 2 580 zł",
    p1_price_small="&nbsp;<small>za m² PU — gładzie, farby, panele, listwy</small>",
    p1_desc="Wykończenie techniczne gotowe do wprowadzenia mebli z IKEA / sklepu — bez zabudów na wymiar.",
    p1_features=[
        "Tynki gipsowe + gładzie premium",
        "Podłogi laminat / winyl LVT wg koszyka",
        "Pierwsze sprzątanie builderskie",
    ],
    p1_btn="Wybieram Move-in Base",
    p2_tier="Pakiet 02",
    p2_name="Signature Finish",
    p2_price="od 3 420 zł",
    p2_price_small="&nbsp;<small>za m² PU — łazienki premium, drzwi, led</small>",
    p2_desc="Komplet łazienek w gresie 60×120, armatura stal nierdzewna, drzwi wewnętrzne, szyny sufitowe z LED.",
    p2_features=[
        "Nadzór koordynatora wnętrz KBN",
        "Pomiary wilgotności i odbiory pokojowe",
        "Rezerwa budżetowa na podłogi hybrydowe premium",
    ],
    p2_btn="Rezerwuję Signature Finish",
    p3_tier="Pakiet 03",
    p3_name="Bespoke Living",
    p3_price="od 4 890 zł",
    p3_price_small="&nbsp;<small>za m² PU — zabudowy, fornir, kamień</small>",
    p3_desc="Indywidualne zabudowy meblowe, okładziny ścienne, detale stolarskie i akustyka pod soft furnishing.",
    p3_features=[
        "Warsztat stolarski partnerski na wymiar",
        "Bookmatch kamienia i detale narożników",
        "Aranżacja finałowa przed sesją foto",
    ],
    p3_btn="Zaplanuj Bespoke Living",
    gallery_h2="""Detale, <span>które domykają</span> wrażenie""",
    gallery_sub="Łazienki, podłogi i zabudowy z realizacji KBN — spójne z budową i instalacjami.",
    gallery_imgs=[
        ("https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1600&q=80", "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=900&q=80", "Jasny salon z dużym przeszkleniem"),
        ("https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1200&q=80", "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=600&q=75", "Łazienka z prysznicem walk-in"),
        ("https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=75", "Kuchnia z wyspą w nowym domu"),
        ("https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&q=80", "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&q=75", "Wnętrze z naturalnym światłem"),
        ("https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&q=80", "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=600&q=75", "Schody i balustrada w domu"),
        ("https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1200&q=80", "https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=600&q=75", "Minimalistyczna sypialnia"),
    ],
    cta_h2="""Masz już <span>wizualizacje</span> czy dopiero inspiracje z Pinterest?""",
    cta_p="Przy wyborze pakietu Signature/Bespoke przygotujemy koszyk próbek materiałów w ciągu 7 dni po spotkaniu.",
)

_svc(
    file="usluga-projektowanie-wnetrz.html",
    title="Projektowanie wnętrz — KBN Signature Homes",
    meta_desc="Projekt wnętrz 3D, dobór materiałów i realizacja koordynowana — KBN Signature Homes, Podkarpacie.",
    hero_img_w2000="https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=2000&q=80",
    breadcrumb="Projektowanie wnętrz",
    h1_inner="""Projektowanie wnętrz <span>pod Twój rytm dnia</span> — wizualizacja + lista zakupów""",
    lead="Tworzymy koncepty, które da się policzyć i zbudować — bez mebli „z kosmosu” i bez konfliktu z instalacjami, które już prowadzimy na budowie.",
    intro_tag="Dlaczego KBN",
    intro_h2="""Projekt to nie render — <span>to harmonogram</span> dostaw szczegółów""",
    intro_p1="Wiemy, jak długo czeka się na laminaty XL i na zamówienia blatów — zakładamy bufory materiałowe w dokumentacji dla Ciebie i budowy.",
    intro_p2="Jeśli KBN realizuje instalacje i wykończenia, projektanci siedzą z kierownikami przy jednym stole — zmianę obwodu Ledy widzisz w tej samej wersji rysunku.",
    bullets=[
        "Inwentaryza laserowa jeśli pracujemy na istniejącej bryle",
        "Opisy wykończeń dla przetargów i porównania",
        "Konsultacja akustyczna uproszczona dla mieszkań dzieci",
        "Współpraca z dostawcami mebli kuchennych na wymiar",
    ],
    aside_h3="Kiedy start",
    aside_p="Najlepiej miesiąc przed wiechą lub przed gruntownym wyburzeniem przegród — dostosujemy ściany i punty elektryczne do ustawienia mebli.",
    pkg_subtitle="Mieszkanie lub dom rzędu ~90–220&nbsp;m² — pakiety liczone za m² powierzchni projektowej (bez tarasów otwartych).",
    pkg_note="Ceny netto ± VAT. Wyjazdy poza Podkarpacie i nadgodziny na budowie w godzinach 22–6 — wg stawki kilometrowej lub umowy.",
    p1_tier="Pakiet 01",
    p1_name="Concept",
    p1_price="od 95 zł",
    p1_price_small="&nbsp;<small>za m² PU — moodboard + układ funkcjonalny 2 iteracje</small>",
    p1_desc="Dwa warianty rozmieszczenia mebla kluczowego oraz tablica materiałów z kartami cenowymi orientacyjnymi.",
    p1_features=[
        "Rzuty czarno-białe CAD",
        "Moodboardy online",
        "Wideokonsultacje lub 2 spotkania stacjonarne",
    ],
    p1_btn="Wybieram Concept",
    p2_tier="Pakiet 02",
    p2_name="Interior Signature",
    p2_price="od 215 zł",
    p2_price_small="&nbsp;<small>za m² PU — wiz 3D, specyfikacja, lista zakupów</small>",
    p2_desc="Komplet foto-realistyczny salonu + kluczowych sypialni, specyfikacja podłóg, ścian, oświetlenia i okładzin.",
    p2_features=[
        "Biblioteka modeli zsynchronizowana z wykonaniami KBN",
        "Raport kolizji z rekuperacją / sufitem podsufitkowym",
        "Jedna tura poprawek w zakresie WIZ gratis",
    ],
    p2_btn="Rezerwuję Interior Signature",
    p3_tier="Pakiet 03",
    p3_name="Design + Site",
    p3_price="od 395 zł",
    p3_price_small="&nbsp;<small>za m² PU — jak Signature + wizyty i nadzór</small>",
    p3_desc="Projekt „pod budowę” z detalami zamówień dla stolarza, wizyty powykonawcze, assist przy odbiorach końcowych.",
    p3_features=[
        "Komunikacja z brukarzem ogrodu przy ciągu wejść",
        "Dobór textile i sztuki w końcowej fazie",
        "Pakiet dokumentacji foto do celów marketingowych inwestora prywatnego",
    ],
    p3_btn="Zaplanuj Design + Site",
    gallery_h2="""Od tablicy <span>do</span> ostatniej poduszki""",
    gallery_sub="Wnętrza o różnych skalach — minimalistyczna baza i detale materiałowe dla domów KBN.",
    gallery_imgs=[
        ("https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1600&q=80", "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&q=80", "Salon designerski z sofą i oknem"),
        ("https://images.unsplash.com/photo-1615873968403-89e068629265?w=1200&q=80", "https://images.unsplash.com/photo-1615873968403-89e068629265?w=600&q=75", "Minimalistyczna jadalnia przy kuchni"),
        ("https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1200&q=80", "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=600&q=75", "Apartament loftowy z mikrocementem"),
        ("https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80", "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=600&q=75", "Kominek elektryczny w nowoczesnym salonie"),
        ("https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&q=80", "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&q=75", "Sypialnia z tapicerowanym panelem ściennym"),
        ("https://images.unsplash.com/photo-1615873968403-89e068629265?w=1200&q=80", "https://images.unsplash.com/photo-1615873968403-89e068629265?w=600&q=75", "Łazienka z okrągłym lustrem i gres XL"),
    ],
    cta_h2="""Wolisz wyglądać <span>jak katalog premium</span> czy rustykalny slow-living?""",
    cta_p="Prześlij 5 referencji z Instagrama oraz budżet mebli — wrócimy z propozycją pakietu i timeline prac graficznych.",
)
